<?php
	$AWS_ACCESS_KEY_ID		= 'AKIAJM4ZD4K5GX6OJJQQ';
	$AWS_SECRET_ACCESS_KEY	= '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';
	$MERCHANT_ID			= 'A3GXSZUBKA3TRJ';
	$MARKETPLACE_ID			= 'ATVPDKIKX0DER';
	$APPLICATION_NAME		= 'DB Order Synchronization';
	$APPLICATION_VERSION	= '0.1';
	$serviceUrl				= 'https://mws.amazonservices.com/Orders/2011-01-01';
?>